<?xml version="1.0" encoding="utf-8"?><Database Name="Mental_Math" Class="MMDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=cmdlhrlt976;Initial Catalog=Mental_Math;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="Mental_MathConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.mytable" Member="mytables">
    <Type Name="mytable">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="videos" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
</Database>